name: 'solar-savers'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - pyarrow
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
    - urllib3
    - matplotlib
    - geopandas
    - pip:
        - dash-vega-components